maptiler/tileserver-gl

Dockerfile
This avoids the arguably risky "curl | bash" with simply adding the repositories directly
=> Avoid curl | bash

src/main.js, src/server.js
I ported this PR direktly in github, without checking the coude out / testing, but it should be OK, I think.
I created this github "organization" to be able to fork the original tileserver, since I got:
"You already have a fork of this repository: efi/tileserver-gl-light"
=> new feature: command line option for bind address

src/main.js, src/server.js
we are using `cors` middleware with default options which works for most
applications, but does not allow for fine tuning (whitelisting origins
etc.)
this change keeps CORS handling as default to preserve compatibility but
also allows for specying `--no-cors` option which makes it possible to
handle CORS in an independent proxy (NGINX, another node app etc.)
=> add `--cors` option to allow for optional CORS handling

src/server.js
The `callback` provided to the main server export is called twice on success (once on `'listening'` and once after 1000 ms).  The callback is not being used elsewhere in the repo, so in case it isn't actually required, this pull request proposes removing it.
It's very possible that I'm missing something about how the callback is used.  No offense if you close this :).
=> Remove unused callback

src/server.js
Minor change, but this makes it easier to use the logged URL if an IPv6 address is used (the literal address is [enclosed in brackets](https://en.wikipedia.org/wiki/IPv6_address#Literal_IPv6_addresses_in_network_resource_identifiers) to avoid conflict with the `:` separator for the port).
E.g.
```
Listening at http://[::]:8080/
```
=> Enclose literal IPv6 addresses in brackets

package.json, src/server.js
I'm opening this PR to hear thoughts on how people think #22 should be implemented.
This brings in [`http-shutdown`](https://www.npmjs.com/package/http-shutdown) for gracefully closing the server before reloading the config.  If there is concern about the extra record keeping for tracking connections, [`server-destroy`](https://www.npmjs.com/package/server-destroy) is slightly lighter alternative, but this would mean a hard shutdown after some fixed timeout.
In order to reload the config and styles, the entire `require.cache` is cleared.  If this is a concern, a more selective cache clearing could work, but I think there would probably be marginal benefit.
I also made it so the `callback` is only called once (previously it was called [on …
=> Reload configuration on SIGHUP

src/serve_rendered.js
This makes it so errors in `serve_rendered.js` are written to `stderr`.  The `return`s are to avoid additional errors when the second arg to the callback is not defined.  It may be that the correct behavior is to reject (at least in [the first case](https://github.com/tschaub/tileserver-gl/blob/de83021c3db53a4b258f119e7f683e51bade02f8/src/serve_rendered.js#L240)) or otherwise handle the error.
=> Log errors to stderr and return

Dockerfile
Dockerfile based on `debian:stretch`, so better to use native `stretch` nodejs repo instead of `jessie` repo.
=> Use debian stretch nodejs repo

docs/config.rst, src/serve_rendered.js
Here's a change to make the raster tile renderer pool sizes configurable in the configuration file. Details of how it works are in the config file diff.
At first I thought for simplicity that I'd use a single value for all scale factors, but I concluded it would have been confusing if the default value depends on the scale factor, but it wouldn't have been configurable at that level. Allowing arrays shorter than `maxScaleFactor` should keep this simple enough to configure.
=> Make raster tile renderer pool sizes configurable

src/serve_rendered.js
A tile in our data is corrupted. As a result its header is not correct, and this causes the server to crash. We know which exact tile is broken in our data, so we can reproduce the problem.
```
zlib.js:560
throw error;
^
Error: incorrect header check
at Zlib._handle.onerror (zlib.js:370:17)
at Unzip.Zlib._processChunk (zlib.js:550:30)
at zlibBufferSync (zlib.js:239:17)
at Object.exports.unzipSync (zlib.js:151:10)
at /usr/src/app/src/serve_rendered.js:185:38
at Statement.<anonymous> (/usr/src/app/node_modules/@mapbox/mbtiles/lib/mbtiles.js:166:20)
Segmentation fault (core dumped)`
```
=> Catch incorrect header exceptions

Dockerfile, run.sh
Node can't be PID 1, else it can't be term'ed and xvfb won't stop nicely.  So, according to https://docs.docker.com/engine/reference/builder/#entrypoint, we need to make sure it's not the bare entrypoint.
Also we need to be sure that run.sh passes the signal through to node, see https://unix.stackexchange.com/questions/146756/forward-sigterm-to-child-in-bash
=> Addresses issue #197, send SIGTERM through to node

src/serve_data.js, test/tiles_data.js
Result status code changed from 404 to 204 when mbtiles error is 'Tile does not exist'  (due to issue #46 )
=> Return 204 when mbtiles error is 'Tile does not exist'

package.json, src/main.js
Default value and coercion order are now inverted.
This seems to be the new undocumented behavior of commander. See: https://github.com/tj/commander.js/pull/829
=> Update commander and devDeps

package.json
According to https://github.com/mapbox/mapbox-gl-native/blob/master/platform/node/CHANGELOG.md there is no broken features.
Previous version is not buildable now.
> @mapbox/mapbox-gl-native@3.5.4 install /home/ubuntu/maps/node_modules/@mapbox/mapbox-gl-native
> node-pre-gyp install --fallback-to-build=false || make node
```
node-pre-gyp ERR! install error 
node-pre-gyp ERR! stack Error: 403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/@mapbox/mapbox-gl-native/v3.5.4/node-v57-linux-x64-Release.tar.gz
```
=> new mapbox-gl-native version

src/main.js
The `public_url` option is not correctly retrieved and make the program crash.
This PR hence fixes #230.
=> Correctly retrieve the public_url parameter on start

src/serve_data.js
The HTTP 1.1 specification states the following on the [204 No content status code definition](https://tools.ietf.org/html/rfc2616#page-60):
> The 204 response MUST NOT include a message-body, and thus is always
>    terminated by the first empty line after the header fields.
Some Vector Tile libraries (at least Mapbox GL Native and Mapbox GL React Native) throw an error if a body message is present on an HTTP response with the 204 status code. This PR removes the body message from the response when an HTTP 204 response is sent.
=> Removes body data from http 204 response

src/main.js, src/server.js
let the user define a log file or a log format:
log file defaults to standard out.
log format defaults to current behavior ('tiny' for production, 'dev' for dev, and not enabled in test)
=> let the user define a log file or a log format

src/main.js, src/serve_rendered.js
Verbose flag used to added additional error messages to critical errors, such as
https://github.com/klokantech/tileserver-gl/issues/323
in the process of cloning the apparent SQLITE_CORRUPT database as follows:
```
!#/bin/sh
#dump command in sqlite3 and pipe to sqlite3 insert into new database
sqlite3 planet.mbtiles ".dump" | sqlite3 new.db
```
=> Use verbose flag to debug corrupted mbtiles

docs/config.rst, src/serve_rendered.js
The issue of cropped labels in raster tiles has been reported in multiple times: #344, #184, #35 #224, etc. I have tried a variety of offered suggestions to resolve the issue, but none worked reliably. 
I ended up solving the problem by adding code to generate larger tiles and then crop them to the right size. This can be controlled via a new `"tileMargin"` option in configuration file.
Maybe this will be useful to someone else.
=> Add tileMargin option

publish.js
Hello!
`tileserver-gl-light` works perfectly with Node.js 12 and 13.
This PR relax the field `engines.node` in its `package.json` file.
We actually use a `tileserver-gl-light` fork in French governement digital services, with this improvement :)
Jerome
=> Relax Node.js compatibility for -light version

src/serve_rendered.js
I'm not sure if there is any other reason why this longstanding issue is not resolved yet. But I figured a pull request with a properly indented fix could help, so here it is. This fixes issue #350.
=> FIx issue #350 Semi-transparent outlines on raw, premultiplied input

src/serve_rendered.js
This is necessary for tileserver to close a connection immediatly on render errors instead of waiting for a timeout in the client. I believe that problem is as at least related to the already closed issue #171.
=> Close connection on erros

README.md, README_light.md, publish.js
I want to build tileserver-gl-light for arm (Raspberry Pi) but I don't run npm publish from publish.js.
I make `--no-publish` option to make only tileserver-gl-light.
I do following:
```
node publish.js --no-publish
cd light
docker buildx build -t tileserver-gl-light:latest --platform linux/amd64,linux/arm/v7 .
```
=> add option to pass npm publish

src/server.js
The data sources structure was changed in the 'dynamic_styles' branch introducing a tileJSON object. Adapt the code filling the preview template to the change to get the correct file format instead of "undefined".
See also f2dc13e.
Fix #440 Preview thumbnail missing for raster data source -- file suffix "undefined"
=> Fix preview thumbnail for raster data sources

src/utils.js
I found another reflected XSS issue which is very similar to one in #461
Example link: https://example.com/?style=%22%3E%3Cscript%3Ealert(2)%3B%3C%2Fscript%3E
=> Fix reflected XSS in 'style' parameter

public/templates/wmts.tmpl
The missing ScaleDenominator causes GeoServer to throw an error when importing the layer.
=> Fix missing ScaleDenominator in wmts.tmpl

src/server.js
variable file does not exist. Backtrace
```
ReferenceError: file is not defined
at serve_style.add (/usr/src/app/src/server.js:139:44)
at Proxy.add (/usr/src/app/src/serve_style.js:115:28)
at addStyle (/usr/src/app/src/server.js:121:31)
at fs.readdir (/usr/src/app/src/server.js:215:11)
at args (fs.js:140:20)
at internal/util.js:370:14
at getDirents (internal/fs/utils.js:149:7)
at FSReqWrap.req.oncomplete (fs.js:775:7)
```
=> fix crash in serveAllFonts

package.json
Before https://github.com/lovell/sharp/commit/e82a585cec48fa7a16e4edcccb1ef9021e27d2ca the server may crash with a segfault when under high load.
---
When testing with https://github.com/tsenart/vegeta found that the server would crash with a segfault in sharp/libvips. Narrowed the issue down to the commit referenced above.
Any version of sharp >=v0.25.2 resolves the problem.
Verified the issue and fix using the project's Dockerfile.
Command used for testing:
`echo 'GET http://localhost:8080/styles/basic-preview/14/8581/5738@2x.png' | vegeta attack -rate 50/s | vegeta report`
=> update sharp to avoid segfault

src/serve_rendered.js
For detailed city rendering we need to render rasterfiles up to and including level 21. Therefore I propose to change the maximum raster level to 22
=> Render up to scale level 22

.dockerignore, Dockerfile, docker-entrypoint.sh
Use newer base images and modify Dockerfile to allow for better caching and smaller image file size. Simplify entry script and run as a non-root user.
=> Streamline Dockerfile for caching and size

docker-entrypoint.sh, docs/usage.rst
Allow `docker kill -s HUP` and `docker-compose kill -s HUP` to reach the node process.
=> Simplify reloading the configuration with docker

package.json
This updates all the packages to their latest release. I think it is important to update these packages and fix our vulnerabilities before out 4.0.0 docker release. Due to the sharp update, the minimum node is 14.15.0 after the updates. 
```
root@mapgen2:/opt/test7/tileserver-gl# npm i
up to date, audited 497 packages in 1s
72 packages are looking for funding
run `npm fund` for details
found 0 vulnerabilities
```
```
root@mapgen2:/opt/test7/tileserver-gl# xvfb-run --server-args="-screen 0 1024x768x24" npm test
> tileserver-gl@3.1.1 test
> mocha test/**.js --timeout 10000
global setup
Starting server
Listening at http://[::]:8888/
Startup complete
Metadata
/health
✔ returns 200
/index.json is array of TileJSONs
✔ is json
✔ is non-empty array
/rendered.json is array of TileJSONs
✔ is json
✔ …
```
=> Update all packages to their latest release

src/serve_rendered.js
this fixes Bug with tileMargin setting at level 3 #549
=> Fix rendering with tileMargin on top and bottom border of map

public/templates/index.tmpl
It's a trivial fix but very useful when the TileServer-GL is deployed behind a proxy and started with `--public_url`
=> Fix URL to WMTS capabilities to be based on public URL

src/main.js, src/serve_data.js, src/serve_rendered.js
Open mbtiles in readonly mode as tileserver-gl never writes to them.
I'm not sure if there are any real benefits to this, but I figured it can't hurt.
=> Open mbtiles in readonly mode

src/serve_rendered.js
Check to see if tileJSON already has a particular attribution before appending it again.
Longer term I'd probably keep `attributions` in an array and `join(' | ')` at the end, but we'd probably need some more cleanup before that is viable.
=> Don't include duplicate attributions

.dockerignore, Dockerfile, Dockerfile_light, Dockerfile_test, docker-entrypoint.sh
This moves the docker images from a node debian image to an ubuntu image. This makes it so libjpeg-turbo8 and libicu66 don't have to be sideloaded into debian to get it to work with maplibre-native. 
Due to no longer using a node image, I had to install my own node. I decided to use nodesource since it seems to be a recommended way by [nodejs.org](https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions)
The original image ran as a node user, which is recommended for security. I tried to do the same in these images, but I had to make the users and group since they do not exist by default.
=> Move docker images to ubuntu

docs/config.rst, docs/endpoints.rst, package.json, src/serve_rendered.js, src/server.js, test/static.js
I have Extended the Static-Images Endpoint with the following capabilities:
- Optional border with configurable color and width for paths via the `border` and `borderwidth` parameters
- Optional markers with the following configurable options:
- Icon provided locally via the icons path or as a hyperlink (enabled via `allowRemoteMarkerIcons` setting)
- Scale of the image relative to its original size
- Offset in pixels
- Linecap of the path https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/lineCap
- Linejoin of the path https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/lineJoin
- Capability to provide multiple paths
- Maximum zoom level if autofit is selected when providing a path
Additional Changes:
- In order to keep performance drawing of …
=> Extended Static-Images Endpoint

src/serve_rendered.js
I meant to simplify this canvas import before https://github.com/maptiler/tileserver-gl/pull/606 was merged, but it got missed.
=> Simplify canvas import in serve_rendered.js

Dockerfile, Dockerfile_light, package-lock.json
Changes "--production" to "--omit=dev" to avoid docker build warning.
Adds a package-lock.json to the project.. Copy package-lock.json to docker it exists.
=> Fix 'use omit=dev' warning. copy package-lock.json if it exists

Dockerfile, Dockerfile_light
Currently, if we run the container without mounting a volume, it fails with the following as /data is owned by root:
```
docker run --rm --pull always maptiler/tileserver-gl
latest: Pulling from maptiler/tileserver-gl
Digest: sha256:6bc09421fca44ef603ba174eb7b3e988464a73423ec56126fd3e771d4db370a8
Status: Image is up to date for maptiler/tileserver-gl:latest
Starting tileserver-gl v4.1.2
No MBTiles found
[DEMO] Downloading sample data (zurich_switzerland.mbtiles) from https://github.com/maptiler/tileserver-gl/releases/download/v1.3.0/zurich_switzerland.mbtiles
node:events:491
throw er; // Unhandled 'error' event
^
Error: EACCES: permission denied, open 'zurich_switzerland.mbtiles'
Emitted 'error' event on WriteStream instance at:
at WriteStream.onerror (node:internal/streams/legacy:62:12) …
```
=> chown /data volume in Dockerfiles

package.json, publish.js
Yep, I too came across this issue in setting up tileserver-gl internally! Sorry about that.
Signed-off-by: Vinayak Kulkarni <19776877+vinayakkulkarni@users.noreply.github.com>
=> fix: issue with `husky install`

Dockerfile, Dockerfile_light, README.md, docker-entrypoint.sh, docker-entrypoint_light.sh, docs/installation.rst, package-lock.json, package.json, run.sh, src/healthcheck.js
This PR moves the docker images to use the default 8080 port and updates all the documentation. Opening on port 80 usually requires root access, so moving it to port 8080 makes it easier to start as a non-root user.  I think it also makes it visually easier to understand, since the prompt "Listening at http://[::]:8080/" will actually match the port the user needs to go to to access the server.
There are several issues and PRs that would be helped by moving the default port to 8080, ex
https://github.com/maptiler/tileserver-gl/issues/573
https://github.com/maptiler/tileserver-gl/pull/578
https://github.com/maptiler/tileserver-gl/issues/503
My only concern with this is it is somewhat of a breaking change for users expecting the docker to start on port 80, but I think this will be better …
=> change docker to use port 8080 by default

package-lock.json, package.json, src/serve_data.js, src/serve_font.js, src/serve_rendered.js
Fixes https://github.com/maptiler/tileserver-gl/issues/642.
The issue is that if we could not find a font stack, we were rejecting with an error that included the passed fontstack name. We then sent that error back to the user as plaintext, but in not setting a `content-type` header, browsers guess the response is html and would try to render the fontstack name as html.
I audited the rest of the codebase to find other places where we might potentially reflect back user-supplied data and changed those to always set `content-type: text/plain`. I'd also be amenable to _always_ setting `content-type: text/plain` for any response that is not json and is not explicitly trying to render some other format.
=> fix: Ensure font serving does not reflect userdata-derived errors as HTML

.github/workflows/release.yml
This code to get the package version was accidently omitted from the workflow. This is needed right now to get the version for the docker publish.
I would like to replace this with a automated version bump eventually, but for now this in needed
=> add back missing PACKAGE_VERSION

src/serve_rendered.js
Fix for https://github.com/maptiler/tileserver-gl/issues/649
In maplibre-native there has been code added which limits maps in 'tile mode' to a single tile. This means the TileMargin option does not work because it extends beyond a single tile.  This change forces tileserver to use the static renderer when TileMargin is set. This allows maplibre-native to render beyond the single tile and allows TileMargin to work
For example, without this change, a file generated by tilemaker has labels clipped like
After this change, and setting TileMargin to 10, it looks like this
=> allow tileMargin option

.github/workflows/ct.yml, Dockerfile, Dockerfile_light, Dockerfile_test, README.md, docs/installation.rst, package.json
This PR raises the recommended node version to 18.  I had tested moving to node 18 a while back, but at the time it did not work (I think due to canvas). I tested again today and it seems to work now.  If it works I think it makes sense to raise the default node we recommend, since Node 18 is supported form much longer than Node 16 (2y vs 6m).
I have also added a docker build to the ct test, so it is possible to see if changes like this work on both x64 and arm64.
=> Update to node 18, add docker build test

public/templates/data.tmpl, public/templates/index.tmpl, public/templates/viewer.tmpl
Fixes #532.
Using handlebars within javascript is pretty difficult to protect against, so this sidesteps it by using javascript to pull the query param off the page location and append to the RTL URL.
I used a regex because I thought perhaps this page was aiming for compatibility with very old browsers. If that's not the case, we could parse using `URLSearchParams` or something.
=> Fix xss due to handlebars variables in javascript

src/serve_data.js
When requesting a `geojson` tile as specified in the tile with URL such as:
```
http://localhost:8080/data/v3/10/511/513.geojson
```
tileserver-gl currently throws:
```
file:///Users/danielkao/Repos/tileserver-gl/src/serve_data.js:87
const tile = new VectorTile(new Pbf(data));
^
TypeError: VectorTile is not a constructor
at file:///Users/danielkao/Repos/tileserver-gl/src/serve_data.js:87:30
at Statement.<anonymous> (/Users/danielkao/Repos/tileserver-gl/node_modules/@mapbox/mbtiles/lib/mbtiles.js:196:20)
Node.js v18.13.0
```
I did a little digging and realized that `VectorTile` was not being imported correctly. This fixes it.
Signed-off-by: Daniel Kao <dkao@diplateevo.com>
=> fix: fix vectortile constructor

src/utils.js
This PR fixes support for overriding the hostname by sending `X-Forwarded-Host` http header. 
- Resolves https://github.com/maptiler/tileserver-gl/pull/273 and https://github.com/maptiler/tileserver-gl/issues/119
This implementation preserves the port information, which is necessary for local development and production deployment which use a port other than 80. This was the only issue which prevented the PR above to be merged.
Signed-off-by: Manuel Roth <manuelroth@hotmail.ch>
=> fix: support for `X-Forwarded-Host` http header

docs/deployment.rst
Added basic examples to Caching and Reverse Proxy sections. 
Caching with cloudflare and nginx. Nginx reverse proxy setup for HTTPS.
=> Caching and reverse proxy examples deployment.rst

docker-entrypoint.sh, docker-entrypoint_light.sh
Avoid implementing a complex signal relaying mechanism in `docker-entrypoint*.sh`.
Instead, the shell scripts perform `exec node ...` and the `node` process receives the signals directly from Docker
Related to #560, #575, which were my initial implementation.
=> Simplify signal handling

Dockerfile_light
I found a permission issue in https://github.com/maptiler/tileserver-gl/issues/745#issuecomment-1437945933 which seems to be caused by the permissions on the 'content-type" dependency files having a high UID, non root user as owner. I was able to fix this by [chmod'ing the /usr/src/app to root](https://github.com/maptiler/tileserver-gl/blob/989944070f8229cd70268819430865f370b8f3c5/Dockerfile#L51).
However, I was doing more testing and found this issue also applies to the tileserver-light package. This updates the light dockerfile so it can work again and does some reformatting.
=> Update Dockerfile_light to fix rootless/podman

LICENSE.md, docs/conf.py
These change can be viewed easier here https://github.com/WifiDB/tileserver-gl/blob/license_update/LICENSE.md
I update the license file to reflect the use of 'maplibre-gl-native' instead of 'mapbox-gl-native'. I went though the following urls and pulled over any relevent license info.
https://github.com/maplibre/maplibre-gl-native/blob/main/LICENSE.md
https://github.com/maplibre/maplibre-gl-native/blob/main/LICENSE.mbgl-core.md
There were things the original tileserver-gl license mentioned that did not exist in the maplibre license, but I know we still use (GLFW, libc++,libcurl, libjpeg-turbo,libpng,libuv,libzip). I left these in..
There are a few things i think could be remvoed, but I'm not sure about (LOST,Mapbox iOS SDK). I left these in for now.
I reformatted these to make the license …
=> Update license from mapbox to maplibre

docker-entrypoint.sh
fix error:
what(): Failed to open X display
by deleting the .X99-lock file at the start of the container
=> fix: Failed to open X display when restarting container

src/serve_rendered.js
Use the center and zoom values from the style json as default for the center in the tilejson of the rendered map. This is especially useful for serveAllStyles where there is no other way to set this values explicitly.
=> Use center and zoom from style json

.github/workflows/pipeline.yml
=> chore: use local workflow instead of repo workflow

docs/endpoints.rst
Hello, this is just a small markup fix. There was a Markdown link markup in the reStructuredText file.
- Site: Available endpoints — TileServer GL 1.0 documentation - https://maptiler-tileserver.readthedocs.io/en/latest/endpoints.html#static-images
- File: https://github.com/maptiler/tileserver-gl/blob/master/docs/endpoints.rst
**Before**
**After**
=> docs: fix link markup in endpoints.rst

src/serve_rendered.js
Each path was rendered with each path style, drawing over the correctly styled path. Now each path gets only rendered once with the specific path style.
This is now possible:
With this URL:
```
http://localhost:8080/styles/basic-preview/static/auto/750x250@2x.jpg?path=stroke:yellow|width:2|fill:green|5.9,45.8|5.9,47.8|10.5,47.8|10.5,45.8|5.9,45.8&path=stroke:blue|width:3|fill:red|4.9,44.8|4.9,46.8|9.5,46.8|9.5,44.8|4.9,44.8
```
=> Static images: Allow styling each path differently

src/serve_rendered.js
fixes #981 
Use a try/catch for async functions and passes the error to next. 
Background:
By default, express does not catch errors in async functions, so I added try catches to these functions and forward them to the next handler.
Also see this expressjs guide: https://expressjs.com/en/guide/error-handling.html
Unfortunately, the changes look horrible, but I only added the try/catch.
Here is my local git diff if you ignore whitespaces.
=> fix: don't crash the server on processing issues

docs/endpoints.rst, src/serve_rendered.js, test/static.js
Fixes #980 
Don't split static image encoded path on pipe or comma. I t hink we can't support fill, stroke, and width in combination with encoded polyline, so we should remove it. The encoded polyline can contain all ASCI character, so it can contain `| ` or `,`, splitting on these characters destroys the polyline and will lead to incorrect render results.
=> fix: incorrect polyline decoding

docs/config.rst, src/serve_rendered.js
Adds a new config option `staticAttributionText` that is used for generating the attribution in the static images API.
Open to any suggestions on the option naming, or styling choices. Tried to keep the style as close to default web attribution as possible.
Here's what the `staticAttributionText` looks like:
Here's what the default `watermark` looks like:
=> Add support for stylized attribution text for static images

docs/config.rst, src/serve_rendered.js
An extension of https://github.com/maptiler/tileserver-gl/pull/619 to allow Base64 images to be rendered to static maps.
Also added `allowInlineMarkerImages` config to enable or disable the feature. Open to other variable names
=> Allow base 64 url as images for static maps

docs/endpoints.rst, src/serve_rendered.js, src/serve_style.js, test/static.js
This is a slight simplification of the code.
The explanation is here: https://github.com/maptiler/tileserver-gl/issues/981#issuecomment-1735675052
I tested it very basically. I just looked at a few static maps from my history.
=> chore: cleanup useless decodeURIComponent() calls

package-lock.json, package.json, src/main.js, src/serve_rendered.js
This is a cherry pick of the PR https://github.com/acalcutt/tileserver-gl/pull/284 submitted by @mjj203 in my old fork. I have updated it a little to fix some things changed in the current release.
This replaces request, which is unmaintained and has serveral vulnerabilies, with axios.
Fixes https://github.com/maptiler/tileserver-gl/issues/1006
=> Replace request with axios

public/templates/index.tmpl, src/serve_style.js
On the index page, the WTMS link in the Data section can never be displayed.
It seems to be a remnant of very early days.
It used to point to Maptiler servers, just like the WMTS link in the Style sections used to.
=> Clean error message, remove outdated data wmts

src/serve_rendered.js
Maplibre-native outputs premultiplied pixels values. The sharp library did not support it so we added code to cancel the alpha premultiplication. Note that this can only visible on raster tiles (and probably static maps).
The sharp library now supports premultiplied pixels with the right config. Let's use it: it should be faster and easier to maintain.
Feature announced here:
https://github.com/lovell/sharp/issues/1599#issuecomment-837004081
Feature developped here by @mnutt:
https://github.com/lovell/sharp/pull/2685
For reference, here is the same zone when premultiplication is not cancelled and `premultiplied: true` is not set.
=> Simplify alpha premultiplication, now supported by sharp

src/serve_rendered.js
The order of imports changed in PR #1062.
This causes a crash on ARM platforms during raster rendering.
To reproduce, load rendered image. The home page also triggers the crash through thumbnail rendering.
This PR fixes it, with a comment to minimize the chance of regression.
=> Fix crash on ARM during rendering

public/templates/index.tmpl, src/main.js, src/pmtiles_adapter.js, src/serve_data.js, src/serve_font.js, src/serve_rendered.js, src/serve_style.js, src/server.js, src/utils.js
Commits in this PR clean up the code in stages:
- Convert some promises to async/await in some places where .then() subsisted.
- Compact arguments for renderOverlay and respondImage (2 lines instead of 12, repeated multiple times)
- Remove duplicated field names to simplify code
- Remove unused opt_nokey arg
- Apply camelCase to function and variable names
=> Code cleaning: more idiomatic, a bit shorter

.github/workflows/ci.yml, .github/workflows/ct.yml, .github/workflows/release.yml, Dockerfile, Dockerfile_light, Dockerfile_test, docs/installation.rst, package-lock.json, package.json
I recently worked with the maplibre-native team to make a new node release, [node-v5.3.0](https://github.com/maplibre/maplibre-native/releases/tag/node-v5.3.0). This new maplibre-native adds node 20 support. It is also built on Ubuntu 22.04
For tileserver-gl, this means new OS requirements for linux. It also means we can move up to node 20.  The attached changes updates tileserver-gl docker to ubuntu:jammy (22.04) and node 20 . It also updates package.json and documentation to reflect the new requirements.
If anyone has a change to test this release, please let me know how it goes.
=> Update Maplibre-Native to v5.3.0

docs/endpoints.rst, package-lock.json, package.json, public/templates/data.tmpl, public/templates/index.tmpl, public/templates/viewer.tmpl, public/templates/wmts.tmpl, src/serve_data.js, src/serve_rendered.js, src/server.js, src/utils.js, test/tiles_rendered.js
This is my attempt to add 512px raster tile support to TileServer-GL. It is a continuation of https://github.com/maptiler/tileserver-gl/pull/495 , updated for the current branch
`Known issues`
1.) Zoom 0 in 512px raster mode does not work right. I think this does not work because in maplibre tile mode, the renderer is not able to render beyond a single 512x512px tile, but zoom  0 does this thing were it doubles the width height of the previous zoom level tile. In our default tiles this works fine, since in maplibre native the default tile size is 512, but we use smaller 256 size tiles, so doubling doesn't hit this restriction.
I was able to somewhat get around this by forcing zoom 0 to use the static render instead, but the scaling still didn't look quite right
2.) In data view I had no …
=> Add support for 512 sized raster tiles  - v2

package-lock.json, package.json, public/templates/wmts.tmpl
I found I had missed an issue in wmts in https://github.com/maptiler/tileserver-gl/pull/1136
The two issues were the following
1.) Both layers had the same identifier. This seemed to cause the wrong one to be loaded when I tested with arcgis online
2.) 512px tiles were misaligned, and getting 404 'invalid center' errors. I think this was because it was requesting the wrong zoom level tiles. I fixed this by raising the identifier by 1 for all 512pm TileMatixes
Before the wmts enpoint looked like this
But after these changes it looks correct, and I am able to search locations and get the correct place (where before i couldn't)
=> Fix WMTS endpoint issues after 512px tile PR

public/templates/viewer.tmpl, public/templates/wmts.tmpl, src/serve_rendered.js, src/server.js
In testing I found the 512px tiles we just added didn't work when used in maplibre-gl-js as a raster layer with a 512 tileSize. This is because of a zoom level difference between maplibre and leaflet. After some research I found that to use mapbox 512px tiles they usually get used with the leaflet option `zoomOffset: -1`  to make it request the next zoom level down. However, In the current code we were already removing a zoom level for 256px pixels, so it didn't seem needed.  However I realized 512px tiles are supposed to be in the default maplibre-native zoom levels, not zoom - 1 like 256px tiles. Because of the zoom level difference maplibre-js was trying to grab images that didn't exist on the previous zoom level.
This PR reworks the code so 512px uses regular mapbox/maplibre zoom …
=> Fix 512px tiles so they work with maplibre-js raster 512 tilesize

docs/endpoints.rst, src/server.js
https://github.com/maptiler/tileserver-gl/issues/1159 pointed out a bug where the index.json data enpoints were specifying a tile size. Data endpoints do not support TileSize in the url, so this was incorrect.
This PR makes several changes to fix and improve this.
1.) Data endpoints no longer include the TileSize
2.) I have updated the index.json and rendered.json to accept TileSize in the urls
3.) Fixed the url in data.json. Note that data.json does not support TileSize  in the url
With the change in this PR, the endpoints would now look like this
```
http://localhost:8080/index.json (256px rendered tile url with fixed data url)
http://localhost:8080/256/index.json (256px rendered tile url with fixed data url)
http://localhost:8080/512/index.json (512px rendered tile url with fixed data …
```
=> Fix incorrect TileSize in index.json and data.json data urls. Add TileSize option to index.json and rendered.json endpoints for rendered urls.

src/serve_data.js
Fixes exception when format `pmtiles` is used and `GeoJSON` is requested. Here the variable `isGzipped` is always undefined and the check is redundant because the data is already unzipped. See #1187.
=> Fix exception in pmtiles format when GeoJSON is requested

docs/endpoints.rst, src/serve_rendered.js, src/serve_style.js, src/utils.js, test/style.js
maplibre-gl-native node-v5.4.0 adds support for multi-sprites ( https://maplibre.org/maplibre-style-spec/sprite/#multiple-sprite-sources ).
This PR allows tileserver-gl to handle an array of local sprites, in a format like
```
"sprite": [
{
"id": "colored",
"url": "{styleJsonFolder}/colored_sprites"
},
{
"id": "default",
"url": "{styleJsonFolder}/sprite"
}
],
```
you can also specify urls, like shown in the style spec
```
"sprite": [
{
"id": "colored",
"url": "https://tiles.wifidb.net/styles/WDB_GPSTRAILS/sprite/colored_sprites"
},
{
"id": "default",
"url": "https://tiles.wifidb.net/styles/WDB_GPSTRAILS/sprite"
}
],
```
**Example**
I updated this ATV trail map to use two different sets of sprites, ['default' and 'colored'](https://github.com/maptiler/tileserver-gl/pull/1232#issue-225468618 …
=> Add support for multi-sprites in styles

src/utils.js
Handling the X-Forwarded-Path header, if provided, in case the tileserver is behind an NGINX served under a subpath, e.g.: /tiles/
=> feat: handle the X-Forwarded-Path header

src/utils.js
Handling the X-Forwarded-Path header, if provided, in case the tileserver is behind a reverse-proxy served under a subpath, e.g.: /tiles/
In PR #1197 already added support for tiles urls.
This PR add support for urls in style files
=> feat: add support for X-Forwarded-Path in style urls

package-lock.json, package.json, src/utils.js
- Use `@jsse/pbfont` instead of `@mapbox/glyph-pbf-composite`
- Fixes https://github.com/maptiler/tileserver-gl/issues/1268
=> feat: use `@jsse/pbfont` instead of `@mapbox/glyph-pbf-composite`

public/resources/index.css
This makes the assets usable when the server is being served under a subdirectory (see #1239).
=> fix: use relative URLs in CSS

src/main.js, src/promises.js, src/serve_data.js, src/serve_rendered.js, src/serve_style.js, src/utils.js
These were a bunch of `*Sync` calls that were rather easy to convert to promisified ones, either via `util.promisify` or just `node:fs/promises`.
There's at least one more place I didn't touch, solely because it would have required refactoring all of `server.js::start` to be async.
There are other places left (out of scope of this PR) where e.g. callback async could be converted to promises, etc.
=> fix: avoid synchronous calls where possible

docs/config.rst, src/serve_rendered.js
Per the (brief) discussion https://github.com/maptiler/tileserver-gl/discussions/1281, this PR replaces the `formatQuality` option in the config file with `formatOptions`. 
The documentation is also updated with examples for the previous JPEG and WebP quality settings as well as the new PNG options.
=> Replace `formatQuality` with `formatOptions` for additional configurability

src/main.js, src/mbtiles_wrapper.js, src/serve_data.js, src/serve_rendered.js
This adds a small wrapper around the `@mapbox/mbtiles` MBTiles class to promisify opening them (instead of callback pyramids).
This opens up avenues to further DRY out the code and make things more async and modern.
=> refactor: add promisified wrapper for MBTiles

package-lock.json, package.json, public/files/index.html
.gitignore gets ignored when the npm package gets published. This causes the public/files folder added in https://github.com/maptiler/tileserver-gl/pull/1326 to not exist, which is problem when using the npm package directly as a global install.
This PR changes the placeholder file to a blank index file, which make the folder get included.
This should fix this error in v4.13.2 which is caused by the files folder not being included
=> Fix: Use blank index to make sure 'public/files/' folder exists in npm package

docs/config.rst, src/serve_rendered.js
Adds support for progessive rendering of static jpeg images via the ``formatOptions``.
In my testing, progressive jpegs were ~2% smaller in filesize than their non-progressive counterparts.
They also 'feel' faster because they become more sharp while loading instead of loading in rows from top to bottom.
Also updated the section in the docs.
=> feat: add progressive rendering option for static jpeg images

docs/config.rst, docs/endpoints.rst, package.json, public/resources/index.css, public/templates/data.tmpl, public/templates/index.tmpl, src/serve_data.js, src/server.js, src/utils.js
This PR will add 
- a preview for terrain data (in addition to the current raw data preview)
- highlight color is based on the encoding
- a simple elevation api based on served terrain data
- includes a link on the index page
- for details, see endpoints.rst
Both require configured encoding (see config.rst).
In general this adds just some eye candy and an "inspect" function for terrain like the geojson endpoint.
=> Feature: Terrain Preview and simple Elevation Query

src/utils.js
Fixes #1422 
Hello, I've opened this PR to add support for the `X-Forwarded-Port` which can be very helpful when setting up a proxy in front of the tileserver. This is especially useful when the proxy and the tileserver are running on different ports.
=> feat: add support for x-forward-port header

public/resources/elevation-control.js, public/templates/data.tmpl, src/serve_data.js
I added a Info field to the elevation preview, which queries the elevation api with coordinates.
During the implementation I stumbled over various issues:
- pmtile coordinates weren't working (just tiles)
- pixel calculation was not working
- swapped lat / long in coordinate input
- use of static tileSize is not a good idea
- the limitation by zoom is not needed for coordinate api
=> Fix Elevation API and extend Elevation Preview

Dockerfile, Dockerfile_test, package-lock.json, package.json
I updated the node version of the builder to node 22 in https://github.com/maptiler/tileserver-gl/pull/1438, but forgot to update it in the final image, so docker build is failing with this error v5.1.0
=> Fix wrong node version in docker final image.

docs/endpoints.rst, public/templates/data.tmpl, public/templates/index.tmpl, src/serve_data.js, src/serve_light.js, src/serve_rendered.js, src/server.js, src/utils.js
- Move elevation calculation to `serve_rendered` and stub in `serve_light` due to use of `canvas` and `sharp`
- Elevation API is not available for light!
Possible fix for #1448
=> Fix broken light (invalid use of heavy dependencies)

src/server.js
Since #1429  the start function ["async function start(opts)"](https://github.com/maptiler/tileserver-gl/blame/9bb270b6c577576324046c76303b0d20a9654326/src/server.js#L42) is async, so we have to (a)wait for it during reload otherwise the object is incomplete and the tileserver crashes.
=> Fix SIGHUP (broken since 5.1.x)

src/serve_light.js, src/serve_rendered.js, src/server.js
This addresses #585 and may address #1383.
I stepped down the code and found out, that the memory issue does not apply to the light build. After some debugging I found
https://github.com/maptiler/tileserver-gl/blob/a245126c20400e76d851e269c0381dbdde926b5e/src/serve_rendered.js#L1060
and 
https://github.com/maptiler/tileserver-gl/blob/a245126c20400e76d851e269c0381dbdde926b5e/src/serve_rendered.js#L1220
I assumed that these are not found by the garbage collector because there is a reference somewhere, to I added an explicit cleanup function `clear`, which required the before inaccessible `serving` to handle the `repo`.
As a result I have no more increasing memory with reloading by SIGHUP.
=> Fix SIGUP Memory Leak

.github/workflows/ci.yml
It looks like canvas is failing in the ci due to it trying to build from source and not having the require dependencies. This PR add the canvas dependencies  to the ci workflow, like already exist in the ct workflow where the npm install was working.
=> fix ci - add canvas build dependencies to ci workflow

src/serve_data.js
We were stuck receiving the unimplemented type 3 error when updating to version 5.x. Moved the isGzipped condition outside the tileJSONformat condition and removed content-encoding headers resolves the issue.
=> fix: resolves Unimplemented type: 3 error for geojson format

CHANGELOG.md, package-lock.json, package.json, publish.js
As stated in #1488 the remove of the 'prepare' script breaks the light npm build. This PR reverts the change.
=> Fix invalid Delete of 'prepare' Script required for Light Build

.github/workflows/ct.yml, CHANGELOG.md, package-lock.json, package.json
Second attempt to fix https://github.com/maptiler/tileserver-gl/issues/1488
When tileserver-gl is installed as a global package, it does not run the prepare scripts (as npm intends). this means none of the js files get copied. 
The prepare script should make these files get included in the published package, but because we included them in .gitignore they are getting excluded.
I have read having specifying the files though package.json is preferable to making a .npmignore that differs from .gitignore, so that is what this PR does. I have also added a test publish to the ct workflow, so we can see the files that will be published.
=> Include public\resources js files on npm publish by specifying included files in package.json

CHANGELOG.md, package-lock.json, package.json
Bump version so failed tileserver-light docker build can be republished
=> v5.3.0-pre.1

src/serve_rendered.js
1.  This PR would  add to the Tile JSON implementation:
i. `tileSize`
2.  The [TileJSON 3.0.0](https://github.com/mapbox/tilejson-spec/tree/master/3.0.0) spec is missing a Tile Size concept for rasters.
i. There is discussion at [tilejson-spec#26](https://github.com/mapbox/tilejson-spec/issues/26).  
ii. The Sources spec for [Mapbox](https://docs.mapbox.com/style-spec/reference/sources/#raster-array-tileSize) & [MapLibre](https://maplibre.org/maplibre-style-spec/sources/#tilesize) make use of `tileSize`.  
---
Using the default Zurich tile set with a basic preview.  Paths are mentioned in the docs at [Rendered Tiles](https://tileserver.readthedocs.io/en/latest/endpoints.html#rendered-tiles).
> "*The optional tile size `/{tileSize}` (ex. `/256`, `/512`). If omitted, tileSize defaults to …
=> Rasters: Add `tileSize` to TileJSON

Dockerfile
To fix memory allocations when using raster tiles, I've updated the memory allocator to Jemalloc. 
Discussion can be found [here](https://github.com/maptiler/tileserver-gl/issues/1565)
=> Use jemalloc as memory allocator

CHANGELOG.md, package-lock.json, package.json
A new release workflow was added in https://github.com/maptiler/tileserver-gl/pull/1685 . I have tested it in my fork, but this PR will test it here.
=> bump version to test release workflow
