maptiler/tileserver-gl

docs/installation.rst
=> adding info for OSX setup

public/templates/data.tmpl
Point features weren't visualized any way so here's a pull request for adding a simple circle symbol.
=> X-Ray style: add circle symbols for point layers

src/serve_rendered.js, src/serve_style.js
With this commit code will have right behaviour with external vector tiles.
See: https://github.com/klokantech/tileserver-gl/issues/91#issuecomment-267939138
=> Fix: Right code for working with external vector tiles.

src/serve_rendered.js
When rendering raster tiles, if a style is configured with a source that returns a non-`200` response, the mbgl callback is [called with `{data: new Buffer(0)}`](https://github.com/klokantech/tileserver-gl/blob/bb09f3df644d5279a83dae990c9e6739ccf97cca/src/serve_rendered.js#L160).  If the source tile format is PNG or JPEG, this results in a message like this from mbgl:
```js
{ 
class: 'Style',
severity: 'ERROR',
text: 'Failed to load tile 3/6/5=>3 for source mosaic: unsupported image type'
}
```
And no response from tileserver-gl.
See https://github.com/klokantech/tileserver-gl/issues/171#issuecomment-323847064 for an example style.  If the source results in anything but a 200 with an image, tileserver-gl logs an error and does not generate a response.
I've put together a fix that returns …
=> Try to create the appropriate data type on http errors

src/serve_data.js, src/serve_font.js, src/serve_rendered.js, src/server.js, src/utils.js
This makes it so promises are more consistently rejected on error and adds promise rejection handling.
=> Handle promise rejection

src/main.js, src/server.js
Adding command option -s, --silent to stop logging successful requests.
=> Silent mode (do not log requests with status == 200)

docs/usage.rst
I just saw:
https://github.com/klokantech/tileserver-gl/pull/269
this is a simple doc fix.
I take the chance to ask you if there is any intreset in adding a `/styles/` endpoint to tileserver-gl.
I ask the question because I think it could simplify the integration with `maputnik`.
What do you think?
=> Add silent to doc

public/resources/index.css
Improve text display when you have long titles.
Before:
After:
=> Break all on long title and item

Dockerfile, Dockerfile_light, Dockerfile_test, package.json, src/serve_rendered.js
use node10 (latest node that has binary built @mapbox/mapbox-gl-native v5.0.2)
use latest canvas and sharp API
=> Upgrade to node10, latest dependencies

src/main.js, src/serve_data.js, src/serve_font.js, src/serve_rendered.js, src/serve_style.js, src/server.js, src/utils.js
This should be merged after #403 
* `var`  ->  `let` / `const`
* `[].forEach`  ->  `for (... of ...)`
* `'...' + var`  ->  template strings  \`...${var}\`
* function  ->  arrow functions `=>`
* use `===` and `!==`  instead of `==` and `!=`
=> Update code to ES6

docs/usage.rst
Added missing documentation line for public_url.
=> Updated usage.rst to reflect public_url parameter

run.sh
=> Increase initial timeout - xvfbMaxStartWaitTime

docs/config.rst
and enabled syntax highlighting
=> fixed small errors

src/serve_style.js
this make some setups easier becouse sprites can be handeld
like any other ressources
=> add api key to sprite ressources in style json

docs/usage.rst
Based on https://github.com/maptiler/tileserver-gl/issues/420#issuecomment-766332814
=> Document configuration reloading when using docker

docs/conf.py
Let's update the credit - to test documentation rebuild.
=> Docs update & build test

.github/workflows/automerger.yml
Signed-off-by: Vinayak Kulkarni <19776877+vinayakkulkarni@users.noreply.github.com>
=> build: enable auto-merger workflow 🎢

public/resources/index.css, public/resources/leaflet.css, public/templates/data.tmpl, public/templates/index.tmpl, public/templates/viewer.tmpl
Signed-off-by: Vinayak Kulkarni <19776877+vinayakkulkarni@users.noreply.github.com>
=> fix: add `key_query` to static assets 🎉

Dockerfile
=> fix: minor housekeeping 🧽

docs/deployment.rst
Thanks, for the good documentation of this project! These are just a few small changes that I noticed while reading.
=> Fix typos in deployment.rst

src/server.js
=> Ensure ID is maintained over deconstructing object

README_light.md, docs/config.rst, docs/endpoints.rst
Add undocumented options to docs, more details, small fixes.
=> Add undocumented options to docs

package.json, src/healthcheck.js, src/render.js, src/serve_font.js, src/serve_rendered.js, src/utils.js, test/setup.js
This is a first pass at simplifying the `server_rendered.js` file, which has grown quite big.
This PR will be easier to review commit by commit (there is a GitHub button for that).
If necessary I can split each commit in a dedicated PR.
There should have been no functional changes.
=> Extract nested functions and simplify a little

.husky/commit-msg, .husky/pre-push, package-lock.json, package.json
**Please describe the changes this PR makes and why it should be merged:**
**Status and versioning classification:**
- This PR includes non-code changes, mostly affects improved DX.
=> chore: migrate husky to v9

.github/workflows/release.yml, CHANGELOG.md, PUBLISHING.md, package-lock.json, package.json
Add support for prereleases in the release workflow
=> add support for pre-release in release workflow

CHANGELOG.md, package-lock.json, package.json
Test to make sure the workflow is making pre-releases now
=> Test 5.1.0-pre.1

public/resources/elevation-control.js, src/serve_data.js
Limit float decimal places to seven (in preview and api) as discussed in https://github.com/maptiler/tileserver-gl/pull/1425#issuecomment-2614563989
=> Limit Elevation Lat/Long Output Length

.gitignore, CHANGELOG.md, package-lock.json, package.json
=> v5.2.0-pre.0

CHANGELOG.md, package-lock.json, package.json
=> v5.2.0 pre.1

CHANGELOG.md, Dockerfile_light, PUBLISHING.md, package-lock.json, package.json
Puts back a chmod for the entrypoint, which the image does not load without.
=> Fix light version docker entrypoint permissions

public/resources/elevation-control.js, public/templates/data.tmpl
I added a check to prevent off-globe coordinates (using `map.transform.isPointOnMapSurface(e.point)`) and a marker to show the last clicked position.
=> Enable Terrain Preview Elevation API in GlobeView

CHANGELOG.md, package-lock.json, package.json
=> Release v5.4.0-pre.1

CHANGELOG.md, docs/installation.rst, package-lock.json, package.json
=> Release v5.4.0-pre.2

src/serve_rendered.js
Allows sparse response when http/https endpoints return a 410 error. In tileserver-gl we have made the server send a 410 error when a tile doesn't exist to indicate to maplibre-gl-js that it should retry lower tiles. This PR should make maplibre-native behave the same way, which would fix https://github.com/maptiler/tileserver-gl/issues/1627 when using a http/https endpoint.
=> Allow sparse response when http/https endpoints return a 410 error

src/main.js, src/pmtiles_adapter.js, src/serve_data.js, src/serve_rendered.js
=> Add file info to "Wrong magic number" error
